// Product lifecycle states
const PRODUCT_LIFECYCLE = {
  ACTIVE: 'ACTIVE',
  PRICE_REVIEW_PENDING: 'PRICE_REVIEW_PENDING',
  OUT_OF_STOCK: 'OUT_OF_STOCK'
};

// Valid lifecycle transitions
const VALID_LIFECYCLE_TRANSITIONS = {
  [PRODUCT_LIFECYCLE.ACTIVE]: [PRODUCT_LIFECYCLE.PRICE_REVIEW_PENDING, PRODUCT_LIFECYCLE.OUT_OF_STOCK],
  [PRODUCT_LIFECYCLE.PRICE_REVIEW_PENDING]: [PRODUCT_LIFECYCLE.ACTIVE, PRODUCT_LIFECYCLE.OUT_OF_STOCK],
  [PRODUCT_LIFECYCLE.OUT_OF_STOCK]: [PRODUCT_LIFECYCLE.ACTIVE, PRODUCT_LIFECYCLE.PRICE_REVIEW_PENDING]
};

// Suggestion statuses
const SUGGESTION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
};

// Product categories
const PRODUCT_CATEGORY = {
  ELECTRONICS: 'ELECTRONICS',
  APPAREL: 'APPAREL',
  HOME: 'HOME'
};

// Pricing directions
const PRICING_DIRECTION = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  HOLD: 'HOLD'
};

// Trigger reasons
const TRIGGER_REASON = {
  INITIAL: 'INITIAL',
  INVENTORY_LOW: 'INVENTORY_LOW',
  DEMAND_SPIKE: 'DEMAND_SPIKE',
  MANUAL: 'MANUAL'
};

module.exports = {
  PRODUCT_LIFECYCLE,
  VALID_LIFECYCLE_TRANSITIONS,
  SUGGESTION_STATUS,
  PRODUCT_CATEGORY,
  PRICING_DIRECTION,
  TRIGGER_REASON
};